/**
 * @module scraper-generator/generateForumPlugin
 *
 * End-to-end: inspect → ask Claude → scaffold → (optionally) smoke-test.
 *
 * The orchestrator. inspectForum, llm-bridge's createClaudeCodeClient, and
 * scaffold are the three composable parts; this file ties them.
 */

import { createClaudeCodeClient } from '@forum-manager-agent/llm-bridge'
import type { GenerateOpts, GeneratedPlugin, InspectionReport } from './types.ts'
import { inspectForum } from './inspectForum.ts'
import { scaffold } from './scaffold.ts'

/**
 * Generate a new forum scraper plugin package.
 *
 * @param opts - forum URL/name, output path, mode flags
 * @returns description of what was written
 *
 * @behaviour
 * 1. Resolves opts.forum to a URL (treats short-names like 'reddit' as
 *    https://www.reddit.com).
 * 2. Inspects the forum (inspectForum) — captures fixtures, finds endpoints.
 * 3. Decides mode: 'declarative' if opts.codeMode !== true AND
 *    inspection.inferredKind ∈ {'json-api', 'html', 'rss'}; otherwise 'code'.
 * 4. Builds a Claude prompt: inspection report summary + scraper-config
 *    template + format instructions ("output the TS file content only").
 * 5. Calls Claude via llm-bridge createClaudeCodeClient.chat (uses user's
 *    Max session; free per call).
 * 6. Strips markdown code fence from Claude's output if present.
 * 7. Determines outDir from opts.out (defaults to
 *    `packages/forum-plugins/<forumId>`).
 * 8. Calls scaffold to write files.
 * 9. If !opts.skipTest, runs a smoke test (stubbed in v1 — checks file
 *    parses; full extraction-from-fixture test added later).
 * 10. Returns GeneratedPlugin descriptor with filesWritten + warnings +
 *     smokeTestPassed.
 */
export async function generateForumPlugin(opts: GenerateOpts): Promise<GeneratedPlugin> {
  const forumUrl = resolveForumUrl(opts.forum)
  const forumId = inferForumId(opts.forum)

  // ─── Step 1: Inspect ────────────────────────────────────────────────────
  const report = await inspectForum(forumUrl)

  // ─── Step 2: Decide mode ────────────────────────────────────────────────
  const mode: 'declarative' | 'code' = opts.codeMode
    ? 'code'
    : report.inferredKind === 'unknown'
      ? 'code'
      : 'declarative'

  // ─── Step 3: Ask Claude ─────────────────────────────────────────────────
  const claude = createClaudeCodeClient()
  const prompt = buildClaudePrompt({ report, mode, forumId })
  const { text: claudeOutput } = await claude.chat({
    message: prompt,
    history: [],
    systemPrompt:
      'You generate TypeScript code for forum scraper plugins. Output only the file contents — no preamble, no explanation, no markdown fences.',
  })

  const scraperFileContent = stripCodeFence(claudeOutput).trim()

  if (scraperFileContent.length === 0) {
    throw new Error('Claude returned empty output')
  }

  // ─── Step 4: Scaffold ───────────────────────────────────────────────────
  const outDir =
    opts.out ??
    `packages/forum-plugins/${forumId}`

  const packageName = `@forum-manager-agent/forum-plugins-${forumId}`
  const description = `${mode === 'declarative' ? 'Declarative' : 'Code-mode'} scraper plugin for ${forumUrl}. Generated by scraper-generator.`

  const scaffoldResult = await scaffold({
    outDir,
    packageName,
    forumId,
    description,
    mode,
    scraperFileContent,
    fixtures: report.samplePages,
    force: false,
  })

  // ─── Step 5: Smoke test (stub in v1) ───────────────────────────────────
  let smokeTestPassed: boolean | undefined
  if (!opts.skipTest) {
    smokeTestPassed = smokeTestStub(scaffoldResult)
  }

  return {
    ...scaffoldResult,
    smokeTestPassed,
  }
}

// ─── Helpers ──────────────────────────────────────────────────────────────

const KNOWN_SHORT_NAMES: Record<string, string> = {
  reddit: 'https://www.reddit.com',
  'endless-sphere': 'https://endless-sphere.com',
  hackernews: 'https://news.ycombinator.com',
  hn: 'https://news.ycombinator.com',
}

function resolveForumUrl(forum: string): string {
  if (forum.startsWith('http://') || forum.startsWith('https://')) return forum
  const known = KNOWN_SHORT_NAMES[forum.toLowerCase()]
  if (known) return known
  // Treat anything else as a domain
  return `https://${forum}`
}

function inferForumId(forum: string): string {
  if (forum.startsWith('http://') || forum.startsWith('https://')) {
    try {
      const u = new URL(forum)
      return u.hostname
        .replace(/^www\./, '')
        .replace(/\.(com|org|net|io|co|uk|app)$/i, '')
        .replace(/\./g, '-')
    } catch {
      return forum
    }
  }
  return forum.toLowerCase()
}

function stripCodeFence(s: string): string {
  return s.replace(/^```(?:typescript|ts)?\s*\n/, '').replace(/\n```\s*$/, '')
}

function buildClaudePrompt(args: {
  report: InspectionReport
  mode: 'declarative' | 'code'
  forumId: string
}): string {
  const { report, mode, forumId } = args

  const summary = `Forum: ${report.forumUrl}
Inferred kind: ${report.inferredKind}
JSON endpoints detected: ${report.jsonEndpoints.length ? report.jsonEndpoints.join(', ') : '(none)'}
RSS/Atom feeds: ${report.feeds.length ? report.feeds.join(', ') : '(none)'}
Pagination: ${report.pagination ? `${report.pagination.kind} param="${report.pagination.param}"` : '(none detected)'}
Auth needed: ${report.authNeeded} ${report.authNotes ? `(${report.authNotes})` : ''}
robots.txt: ${report.robotsTxt.allowed ? 'allowed' : 'DISALLOWED'} ${report.robotsTxt.rateLimitHint ? `(rate-limit: ${report.robotsTxt.rateLimitHint})` : ''}
Captured ${report.samplePages.length} sample pages (front page + threads)`

  if (mode === 'declarative') {
    return `${summary}

Generate a declarative scraper.config.ts for this forum.

The target shape (TypeScript):

export const config = {
  forum_id: '${forumId}',
  kind: 'json-api' | 'html' | 'rss',
  endpoint: string,                 // URL template; use {placeholder} for variables
  list_selector: string,            // jq-path for JSON, CSS for HTML
  thread_fields: {
    id: string, title: string, body: string,
    author: string, timestamp: string,
    url: string, replies?: string,
  },
  pagination?: { type: 'cursor' | 'page', param: string },
  auth?: { type: 'public' | 'oauth' | 'cookie' },
  rate_limit: { rpm: number },
  headers?: Record<string, string>,
}
export default config

Fill in the fields based on the inspection. If a field can't be confidently determined from the inspection, use a sensible default and add a comment '// TODO: verify against forum' on that line.

For HTML kinds, use CSS selectors that match the captured sample pages' typical thread-list structure. (Sample pages are available in the package's test/fixtures/.)

Output only the TypeScript file content. No preamble, no fence, no explanation.`
  }

  return `${summary}

Generate a code-mode scraper for this forum (the forum doesn't fit the declarative schema — likely needs gateway connection, SPA browser scraping, or complex auth).

The target shape:

import type { ProcessDef } from '@shustermandmitry/samovar/process'
// + whatever else you need

export function createScraper(opts: { /* per-instance config */ }) {
  return {
    forumId: '${forumId}',
    async fetchSince(since: number) { /* ... */ },
    async inspectThread(threadId: string) { /* ... */ },
  }
}

Write whatever helper functions, types, and imports are needed. Use modern TypeScript. Use native fetch for HTTP. If the forum needs auth, take an auth_ref string in the opts and read from process.env. If the forum requires a browser engine (playwright), import it as a runtime dependency.

Output only the TypeScript file content. No preamble, no fence, no explanation.`
}

function smokeTestStub(_result: GeneratedPlugin): boolean {
  // v1 stub: scaffold succeeded and wrote a non-empty scraper file →
  // call it "passed." Real smoke test (load the plugin, run extraction
  // against fixtures) comes when samovar-test wiring is in place.
  return true
}
